version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: steamclone-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  steamclone-api:
    build:
      context: ./SteamClone.Api
      dockerfile: Dockerfile
    container_name: steamclone-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MongoDbSettings__ConnectionString: mongodb://mongodb:27017
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  mongodb_data: